### ISSUE TITLE
Problem with more than one light per loxone lightning controller

### ISSUE THREAD

**Issue by bekli** [ppieczul/org.openhab.binding.loxone#2]
![grafik](https://user-images.githubusercontent.com/33777228/32978429-782f2234-cc42-11e7-937b-56f19c3aa00f.png)

If I create two dimmer Items for this config the first one (for "Deckenleuchte 1 WZ") works and the second doesnt work. There is no difference in the loxone-config of the two lights. This is the case for every room I have more than one dimmable light in the lightning controller. The OnOff Type commands work but the dimming of the second lamp doesnt.

**Comment by ppieczul** [comment]
This issue will be also fixed by this PR
https://github.com/openhab/openhab2-addons/pull/2821

Please let me know if you would like to install it manually and test before
it is in the build

Thanks

**Comment by ppieczul** [comment]
If you try now the binding and openhab from latest unstable build, it should have this issue fixed.
