### ISSUE TITLE
Only Lightning Controller Gen 1 supported?

### ISSUE THREAD

**Issue by bekli** [ppieczul/org.openhab.binding.loxone#3]
In my loxone config I habe many lightning controllers gen 1. They all show up as channels in your binding and that works great! =)
The problem is, that I also already used some of the new lightning controllers in my config. Unfortunately they won't show up as channels.

**Comment by ppieczul** [comment]
There is a PR waiting for merge into openHAB addons that adds this feature
https://github.com/openhab/openhab2-addons/pull/2821

**Comment by ppieczul** [comment]
If you try now the binding and openhab from latest unstable stream, it should support gen 2 controller.
