### ISSUE TITLE
Lighting Controller v2 Mood Switch

### ISSUE THREAD

**Issue by lewisvive** [ppieczul/org.openhab.binding.loxone#4]
This may be me being dumb but I can’t get any of the Mood input switches working in OpenHAB, any ideas?

**Comment by ppieczul** [comment]
@lewisvive Did you solve your issue? What was the reason?

**Comment by lewisvive** [comment]
Hi,

Sort of, it’s not easy to set it up :). I am trying to get Alexa to work so as it needs tags adding. Is there a way to get the UUID to the Names on screen?

Thanks

**Comment by ppieczul** [comment]
Which names and on which screen?

2018-02-07 16:26 GMT+01:00 lewisvive <notifications@github.com>:

> Hi,
>
> Sort of, it’s not easy to set it up :). I am trying to get Alexa to work
> so as it needs tags adding. Is there a way to get the UUID to the Names on
> screen?
>
> Thanks
>
