### ISSUE TITLE
Dimmer device in openhab does not update value within Loxone

### ISSUE THREAD

**Issue by TheSpirit** [ppieczul/org.openhab.binding.loxone#8]
HI.
I have a Dimmer within openhab with a slider.
If i move the slider within openhab, the physical device is dimming, but i do not see the value change within Loxone software.
What is wrong?
Thanks a lot,
Andreas

**Comment by ppieczul** [comment]
That seems to be an issue with Loxone software. If the dimmer is physically working, miniserver must be receiving the commands and steering the dimmer. Then if the Loxone app updates or not lays within the app. 

What you may try to do is to open two loxone apps and see if you change in one does it update in the other. If yes I will see what could be the reason it behaves differently in openHAB. 
Thanks

**Comment by TheSpirit** [comment]
there is some missunderstanding.
the physical dimmer device is hocked to openhab.
i sent post commands from loxone to openhab but the feedback from openhab is not sent back to loxone.
the problem is, there is also a physical dimmer button which is linked to openhab.
so if i use the physical button, the dimmer within openhab is working, but i want to have the feedback within loxone to.
i hope it is more clear now.

**Comment by ppieczul** [comment]
I suppose this is not designed to work that way. The way it is designed is that with Loxone binding in openHAB you can have a representation of controls that are in miniserver. Only for those channels that are automatically created in openHAB from miniserver runtime configuration the state changes will be propagated to Loxone. 
But it is expected that the device is connected to Loxone not openHAB. How do you connect the real dimmer to openHAB and which channels are you using?
Please understand that details of your configuration are obvious to you but completely unknown to me. It would tremendously help if you described your configuration in details.

**Comment by TheSpirit** [comment]
the dimmer binding got an update and now it works just fine.
